spring.application.name=gateway-service

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.ssl.enabled=${RABBITMQ_SSL_ENABLED:false}

telegram.bot-token=${TELEGRAM_BOT_TOKEN}
telegram.api-url=${TELEGRAM_BOT_API_URL}
telegram.secret-token=${TELEGRAM_BOT_SECRET_TOKEN}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}